#!/bin/bash

count_directories=0

for item in ./*; do
    if [ -d "$item" ] && [ "$item" != "./" ] && [ "$item" != "../" ]; then
        count_directories=$((count_directories + 1))
    fi
done

echo " $count_directories"
